apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /data
  storageClassName: static
  accessModes:
  - ReadWriteOnce

  ---
  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-pvc
spec:
  storageClassName: static
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
