apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name | quote }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  replicas: 3
  type: {{ .Values.service.type }}
  selector:
    matchLabels:
      {{- include "helm-charts.selectorLabels" . | nindent 4}}
  template:
    metadata:
      name: {{ .Values.service.name | quote }}
      labels:
        {{- include "helm-charts.labels" . | nindent 4 }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}
          ports:
            {{ .Values.containers.port }}