apiVersion: v1
kind: Service
metadata:
  {{ .Values.service.name }}
spec:
  {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targePort: {{ .Values.service.targetPort}}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "helm-charts.selectorLabels" . | nindent 4 }}